name: Build Validation

on: [push, pull_request]

jobs:
  Validation:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: Test
      run: dotnet test --no-build --configuration ${{ matrix.configuration }}
